// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVrf-38G9sMbDLvc_wggqnB5LyRvbLt3A',
    appId: '1:733179330588:web:6086cbd2d9d374e7a5dfd9',
    messagingSenderId: '733179330588',
    projectId: 'invoice-pay-ef942',
    authDomain: 'invoice-pay-ef942.firebaseapp.com',
    storageBucket: 'invoice-pay-ef942.firebasestorage.app',
    measurementId: 'G-8EF1N9QKQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYCWxF3AU5F_E2kSs0aSWHg96Hzg-k48k',
    appId: '1:733179330588:android:de9a092433bcf529a5dfd9',
    messagingSenderId: '733179330588',
    projectId: 'invoice-pay-ef942',
    storageBucket: 'invoice-pay-ef942.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4IO5wEs1Sace0IUk_lf1W_9H7yinSU3g',
    appId: '1:733179330588:ios:b3711ddb5f2db8cba5dfd9',
    messagingSenderId: '733179330588',
    projectId: 'invoice-pay-ef942',
    storageBucket: 'invoice-pay-ef942.firebasestorage.app',
    iosClientId: '733179330588-jv2rgng60u824b1tumsmep5gs404nr15.apps.googleusercontent.com',
    iosBundleId: 'com.example.invoicePay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4IO5wEs1Sace0IUk_lf1W_9H7yinSU3g',
    appId: '1:733179330588:ios:b3711ddb5f2db8cba5dfd9',
    messagingSenderId: '733179330588',
    projectId: 'invoice-pay-ef942',
    storageBucket: 'invoice-pay-ef942.firebasestorage.app',
    iosClientId: '733179330588-jv2rgng60u824b1tumsmep5gs404nr15.apps.googleusercontent.com',
    iosBundleId: 'com.example.invoicePay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVrf-38G9sMbDLvc_wggqnB5LyRvbLt3A',
    appId: '1:733179330588:web:29b8ba006884f112a5dfd9',
    messagingSenderId: '733179330588',
    projectId: 'invoice-pay-ef942',
    authDomain: 'invoice-pay-ef942.firebaseapp.com',
    storageBucket: 'invoice-pay-ef942.firebasestorage.app',
    measurementId: 'G-5NT2TFBEWP',
  );
}
